/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { ContextId } from "./ContextId.js";

export const CancelContextRequest: core.serialization.ObjectSchema<
    serializers.CancelContextRequest.Raw,
    Cartesia.CancelContextRequest
> = core.serialization.object({
    contextId: core.serialization.property("context_id", ContextId),
    cancel: core.serialization.booleanLiteral(true),
});

export declare namespace CancelContextRequest {
    export interface Raw {
        context_id: ContextId.Raw;
        cancel: true;
    }
}
