/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";

export const FlushId: core.serialization.Schema<serializers.FlushId.Raw, Cartesia.FlushId> =
    core.serialization.number();

export declare namespace FlushId {
    export type Raw = number;
}
