/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";
import { TtsRequestVoiceSpecifier } from "./TtsRequestVoiceSpecifier";
import { SupportedLanguage } from "./SupportedLanguage";
import { WebSocketRawOutputFormat } from "./WebSocketRawOutputFormat";
import { ContextId } from "./ContextId";

export const GenerationRequest: core.serialization.ObjectSchema<
    serializers.GenerationRequest.Raw,
    Cartesia.GenerationRequest
> = core.serialization.object({
    modelId: core.serialization.property("model_id", core.serialization.string()),
    transcript: core.serialization.string(),
    voice: TtsRequestVoiceSpecifier,
    language: SupportedLanguage.optional(),
    outputFormat: core.serialization.property("output_format", WebSocketRawOutputFormat),
    duration: core.serialization.number().optional(),
    contextId: core.serialization.property("context_id", ContextId),
    continue: core.serialization.boolean().optional(),
    addTimestamps: core.serialization.property("add_timestamps", core.serialization.boolean().optional()),
    addPhonemeTimestamps: core.serialization.property(
        "add_phoneme_timestamps",
        core.serialization.boolean().optional()
    ),
});

export declare namespace GenerationRequest {
    interface Raw {
        model_id: string;
        transcript: string;
        voice: TtsRequestVoiceSpecifier.Raw;
        language?: SupportedLanguage.Raw | null;
        output_format: WebSocketRawOutputFormat.Raw;
        duration?: number | null;
        context_id: ContextId.Raw;
        continue?: boolean | null;
        add_timestamps?: boolean | null;
        add_phoneme_timestamps?: boolean | null;
    }
}
