/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";
import { TtsRequestVoiceSpecifier } from "./TtsRequestVoiceSpecifier";
import { SupportedLanguage } from "./SupportedLanguage";
import { WebSocketRawOutputFormat } from "./WebSocketRawOutputFormat";
import { ModelSpeed } from "./ModelSpeed";
import { ContextId } from "./ContextId";

export const GenerationRequest: core.serialization.ObjectSchema<
    serializers.GenerationRequest.Raw,
    Cartesia.GenerationRequest
> = core.serialization.object({
    modelId: core.serialization.property("model_id", core.serialization.string()),
    transcript: core.serialization.unknown(),
    voice: TtsRequestVoiceSpecifier,
    language: SupportedLanguage.optional(),
    outputFormat: core.serialization.property("output_format", WebSocketRawOutputFormat),
    duration: core.serialization.number().optional(),
    speed: ModelSpeed.optional(),
    contextId: core.serialization.property("context_id", ContextId.optional()),
    continue: core.serialization.boolean().optional(),
    maxBufferDelayMs: core.serialization.property("max_buffer_delay_ms", core.serialization.number().optional()),
    flush: core.serialization.boolean().optional(),
    addTimestamps: core.serialization.property("add_timestamps", core.serialization.boolean().optional()),
    addPhonemeTimestamps: core.serialization.property(
        "add_phoneme_timestamps",
        core.serialization.boolean().optional(),
    ),
    useOriginalTimestamps: core.serialization.property(
        "use_original_timestamps",
        core.serialization.boolean().optional(),
    ),
});

export declare namespace GenerationRequest {
    export interface Raw {
        model_id: string;
        transcript?: unknown;
        voice: TtsRequestVoiceSpecifier.Raw;
        language?: SupportedLanguage.Raw | null;
        output_format: WebSocketRawOutputFormat.Raw;
        duration?: number | null;
        speed?: ModelSpeed.Raw | null;
        context_id?: ContextId.Raw | null;
        continue?: boolean | null;
        max_buffer_delay_ms?: number | null;
        flush?: boolean | null;
        add_timestamps?: boolean | null;
        add_phoneme_timestamps?: boolean | null;
        use_original_timestamps?: boolean | null;
    }
}
