/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const ModelSpeed: core.serialization.Schema<serializers.ModelSpeed.Raw, Cartesia.ModelSpeed> =
    core.serialization.enum_(["slow", "normal", "fast"]);

export declare namespace ModelSpeed {
    export type Raw = "slow" | "normal" | "fast";
}
