/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";

export const NaturalSpecifier: core.serialization.Schema<serializers.NaturalSpecifier.Raw, Cartesia.NaturalSpecifier> =
    core.serialization.enum_(["slowest", "slow", "normal", "fast", "fastest"]);

export declare namespace NaturalSpecifier {
    export type Raw = "slowest" | "slow" | "normal" | "fast" | "fastest";
}
