/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";

export const NumericalSpecifier: core.serialization.Schema<
    serializers.NumericalSpecifier.Raw,
    Cartesia.NumericalSpecifier
> = core.serialization.number();

export declare namespace NumericalSpecifier {
    type Raw = number;
}
