/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const PhonemeTimestamps: core.serialization.ObjectSchema<
    serializers.PhonemeTimestamps.Raw,
    Cartesia.PhonemeTimestamps
> = core.serialization.object({
    phonemes: core.serialization.list(core.serialization.string()),
    start: core.serialization.list(core.serialization.number()),
    end: core.serialization.list(core.serialization.number()),
});

export declare namespace PhonemeTimestamps {
    export interface Raw {
        phonemes: string[];
        start: number[];
        end: number[];
    }
}
