/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { RawEncoding } from "./RawEncoding.js";

export const RawOutputFormat: core.serialization.ObjectSchema<
    serializers.RawOutputFormat.Raw,
    Cartesia.RawOutputFormat
> = core.serialization.object({
    encoding: RawEncoding,
    sampleRate: core.serialization.property("sample_rate", core.serialization.number()),
});

export declare namespace RawOutputFormat {
    export interface Raw {
        encoding: RawEncoding.Raw;
        sample_rate: number;
    }
}
