/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";
import { TtsRequestVoiceSpecifier } from "./TtsRequestVoiceSpecifier";
import { SupportedLanguage } from "./SupportedLanguage";
import { OutputFormat } from "./OutputFormat";

export const TtsRequest: core.serialization.ObjectSchema<serializers.TtsRequest.Raw, Cartesia.TtsRequest> =
    core.serialization.object({
        modelId: core.serialization.property("model_id", core.serialization.string()),
        transcript: core.serialization.string(),
        voice: TtsRequestVoiceSpecifier,
        language: SupportedLanguage.optional(),
        outputFormat: core.serialization.property("output_format", OutputFormat),
        duration: core.serialization.number().optional(),
        textCfg: core.serialization.property("text_cfg", core.serialization.number().optional()),
    });

export declare namespace TtsRequest {
    export interface Raw {
        model_id: string;
        transcript: string;
        voice: TtsRequestVoiceSpecifier.Raw;
        language?: SupportedLanguage.Raw | null;
        output_format: OutputFormat.Raw;
        duration?: number | null;
        text_cfg?: number | null;
    }
}
