/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { VoiceId } from "../../voices/types/VoiceId.js";

export const TtsRequestVoiceSpecifier: core.serialization.ObjectSchema<
    serializers.TtsRequestVoiceSpecifier.Raw,
    Cartesia.TtsRequestVoiceSpecifier
> = core.serialization.object({
    mode: core.serialization.stringLiteral("id"),
    id: VoiceId,
});

export declare namespace TtsRequestVoiceSpecifier {
    export interface Raw {
        mode: "id";
        id: VoiceId.Raw;
    }
}
