/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { TtsRequestVoiceSpecifier } from "./TtsRequestVoiceSpecifier.js";
import { SupportedLanguage } from "./SupportedLanguage.js";
import { OutputFormat } from "./OutputFormat.js";
import { ModelSpeed } from "./ModelSpeed.js";

export const TtsRequest: core.serialization.ObjectSchema<serializers.TtsRequest.Raw, Cartesia.TtsRequest> =
    core.serialization.object({
        modelId: core.serialization.property("model_id", core.serialization.string()),
        transcript: core.serialization.string(),
        voice: TtsRequestVoiceSpecifier,
        language: SupportedLanguage.optional(),
        outputFormat: core.serialization.property("output_format", OutputFormat),
        duration: core.serialization.number().optional(),
        speed: ModelSpeed.optional(),
        save: core.serialization.boolean().optional(),
        pronunciationDictIds: core.serialization.property(
            "pronunciation_dict_ids",
            core.serialization.list(core.serialization.string()).optional(),
        ),
    });

export declare namespace TtsRequest {
    export interface Raw {
        model_id: string;
        transcript: string;
        voice: TtsRequestVoiceSpecifier.Raw;
        language?: SupportedLanguage.Raw | null;
        output_format: OutputFormat.Raw;
        duration?: number | null;
        speed?: ModelSpeed.Raw | null;
        save?: boolean | null;
        pronunciation_dict_ids?: string[] | null;
    }
}
