/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { TtsRequestVoiceSpecifier } from "./TtsRequestVoiceSpecifier.js";
import { SupportedLanguage } from "./SupportedLanguage.js";
import { SseOutputFormat } from "./SseOutputFormat.js";
import { ModelSpeed } from "./ModelSpeed.js";
import { ContextId } from "./ContextId.js";

export const TtssseRequest: core.serialization.ObjectSchema<serializers.TtssseRequest.Raw, Cartesia.TtssseRequest> =
    core.serialization.object({
        modelId: core.serialization.property("model_id", core.serialization.string()),
        transcript: core.serialization.string(),
        voice: TtsRequestVoiceSpecifier,
        language: SupportedLanguage.optional(),
        outputFormat: core.serialization.property("output_format", SseOutputFormat),
        duration: core.serialization.number().optional(),
        speed: ModelSpeed.optional(),
        addTimestamps: core.serialization.property("add_timestamps", core.serialization.boolean().optional()),
        addPhonemeTimestamps: core.serialization.property(
            "add_phoneme_timestamps",
            core.serialization.boolean().optional(),
        ),
        useNormalizedTimestamps: core.serialization.property(
            "use_normalized_timestamps",
            core.serialization.boolean().optional(),
        ),
        pronunciationDictIds: core.serialization.property(
            "pronunciation_dict_ids",
            core.serialization.list(core.serialization.string()).optional(),
        ),
        contextId: core.serialization.property("context_id", ContextId.optional()),
    });

export declare namespace TtssseRequest {
    export interface Raw {
        model_id: string;
        transcript: string;
        voice: TtsRequestVoiceSpecifier.Raw;
        language?: SupportedLanguage.Raw | null;
        output_format: SseOutputFormat.Raw;
        duration?: number | null;
        speed?: ModelSpeed.Raw | null;
        add_timestamps?: boolean | null;
        add_phoneme_timestamps?: boolean | null;
        use_normalized_timestamps?: boolean | null;
        pronunciation_dict_ids?: string[] | null;
        context_id?: ContextId.Raw | null;
    }
}
