/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";
import { TtsRequestVoiceSpecifier } from "./TtsRequestVoiceSpecifier";
import { SupportedLanguage } from "./SupportedLanguage";
import { SseOutputFormat } from "./SseOutputFormat";
import { GenerationConfig } from "./GenerationConfig";
import { ModelSpeed } from "./ModelSpeed";
import { ContextId } from "./ContextId";

export const TtssseRequest: core.serialization.ObjectSchema<serializers.TtssseRequest.Raw, Cartesia.TtssseRequest> =
    core.serialization.object({
        modelId: core.serialization.property("model_id", core.serialization.string()),
        transcript: core.serialization.string(),
        voice: TtsRequestVoiceSpecifier,
        language: SupportedLanguage.optional(),
        outputFormat: core.serialization.property("output_format", SseOutputFormat),
        generationConfig: core.serialization.property("generation_config", GenerationConfig.optional()),
        duration: core.serialization.number().optional(),
        speed: ModelSpeed.optional(),
        addTimestamps: core.serialization.property("add_timestamps", core.serialization.boolean().optional()),
        addPhonemeTimestamps: core.serialization.property(
            "add_phoneme_timestamps",
            core.serialization.boolean().optional(),
        ),
        useNormalizedTimestamps: core.serialization.property(
            "use_normalized_timestamps",
            core.serialization.boolean().optional(),
        ),
        contextId: core.serialization.property("context_id", ContextId.optional()),
        pronunciationDictId: core.serialization.property(
            "pronunciation_dict_id",
            core.serialization.string().optional(),
        ),
    });

export declare namespace TtssseRequest {
    export interface Raw {
        model_id: string;
        transcript: string;
        voice: TtsRequestVoiceSpecifier.Raw;
        language?: SupportedLanguage.Raw | null;
        output_format: SseOutputFormat.Raw;
        generation_config?: GenerationConfig.Raw | null;
        duration?: number | null;
        speed?: ModelSpeed.Raw | null;
        add_timestamps?: boolean | null;
        add_phoneme_timestamps?: boolean | null;
        use_normalized_timestamps?: boolean | null;
        context_id?: ContextId.Raw | null;
        pronunciation_dict_id?: string | null;
    }
}
