/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { RawOutputFormat } from "./RawOutputFormat.js";

export const WavOutputFormat: core.serialization.ObjectSchema<
    serializers.WavOutputFormat.Raw,
    Cartesia.WavOutputFormat
> = core.serialization.object({}).extend(RawOutputFormat);

export declare namespace WavOutputFormat {
    export interface Raw extends RawOutputFormat.Raw {}
}
