/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";
import { RawOutputFormat } from "./RawOutputFormat";

export const WavOutputFormat: core.serialization.ObjectSchema<
    serializers.WavOutputFormat.Raw,
    Cartesia.WavOutputFormat
> = core.serialization.object({}).extend(RawOutputFormat);

export declare namespace WavOutputFormat {
    export interface Raw extends RawOutputFormat.Raw {}
}
