/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { GenerationRequest } from "./GenerationRequest.js";
import { CancelContextRequest } from "./CancelContextRequest.js";

export const WebSocketRequest: core.serialization.Schema<serializers.WebSocketRequest.Raw, Cartesia.WebSocketRequest> =
    core.serialization.undiscriminatedUnion([GenerationRequest, CancelContextRequest]);

export declare namespace WebSocketRequest {
    export type Raw = GenerationRequest.Raw | CancelContextRequest.Raw;
}
