/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";
import { WebSocketBaseResponse } from "./WebSocketBaseResponse";

export const WebSocketErrorResponse: core.serialization.ObjectSchema<
    serializers.WebSocketErrorResponse.Raw,
    Cartesia.WebSocketErrorResponse
> = core.serialization
    .object({
        error: core.serialization.string(),
    })
    .extend(WebSocketBaseResponse);

export declare namespace WebSocketErrorResponse {
    export interface Raw extends WebSocketBaseResponse.Raw {
        error: string;
    }
}
