/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";
import { GenerationRequest } from "./GenerationRequest";
import { CancelContextRequest } from "./CancelContextRequest";

export const WebSocketRequest: core.serialization.Schema<serializers.WebSocketRequest.Raw, Cartesia.WebSocketRequest> =
    core.serialization.undiscriminatedUnion([GenerationRequest, CancelContextRequest]);

export declare namespace WebSocketRequest {
    export type Raw = GenerationRequest.Raw | CancelContextRequest.Raw;
}
