/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { WebSocketBaseResponse } from "./WebSocketBaseResponse.js";

export const WebSocketDoneResponse: core.serialization.ObjectSchema<
    serializers.WebSocketDoneResponse.Raw,
    Cartesia.WebSocketDoneResponse
> = core.serialization.object({}).extend(WebSocketBaseResponse);

export declare namespace WebSocketDoneResponse {
    export interface Raw extends WebSocketBaseResponse.Raw {}
}
