/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const WebSocketStreamOptions: core.serialization.ObjectSchema<
    serializers.WebSocketStreamOptions.Raw,
    Cartesia.WebSocketStreamOptions
> = core.serialization.object({
    timeout: core.serialization.number().optional(),
});

export declare namespace WebSocketStreamOptions {
    export interface Raw {
        timeout?: number | null;
    }
}
