/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";
import { RawEncoding } from "./RawEncoding";

export const WebSocketRawOutputFormat: core.serialization.ObjectSchema<
    serializers.WebSocketRawOutputFormat.Raw,
    Cartesia.WebSocketRawOutputFormat
> = core.serialization.object({
    container: core.serialization.stringLiteral("raw"),
    encoding: RawEncoding,
    sampleRate: core.serialization.property("sample_rate", core.serialization.number()),
});

export declare namespace WebSocketRawOutputFormat {
    interface Raw {
        container: "raw";
        encoding: RawEncoding.Raw;
        sample_rate: number;
    }
}
