/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { PhonemeTimestamps } from "./PhonemeTimestamps.js";
import { WebSocketBaseResponse } from "./WebSocketBaseResponse.js";

export const WebSocketPhonemeTimestampsResponse: core.serialization.ObjectSchema<
    serializers.WebSocketPhonemeTimestampsResponse.Raw,
    Cartesia.WebSocketPhonemeTimestampsResponse
> = core.serialization
    .object({
        phonemeTimestamps: core.serialization.property("phoneme_timestamps", PhonemeTimestamps.optional()),
    })
    .extend(WebSocketBaseResponse);

export declare namespace WebSocketPhonemeTimestampsResponse {
    export interface Raw extends WebSocketBaseResponse.Raw {
        phoneme_timestamps?: PhonemeTimestamps.Raw | null;
    }
}
