/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";
import { WebSocketChunkResponse } from "./WebSocketChunkResponse";
import { WebSocketDoneResponse } from "./WebSocketDoneResponse";
import { WebSocketTimestampsResponse } from "./WebSocketTimestampsResponse";
import { WebSocketErrorResponse } from "./WebSocketErrorResponse";

export const WebSocketResponse: core.serialization.Schema<
    serializers.WebSocketResponse.Raw,
    Cartesia.WebSocketResponse
> = core.serialization
    .union("type", {
        chunk: WebSocketChunkResponse,
        done: WebSocketDoneResponse,
        timestamps: WebSocketTimestampsResponse,
        error: WebSocketErrorResponse,
    })
    .transform<Cartesia.WebSocketResponse>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace WebSocketResponse {
    type Raw =
        | WebSocketResponse.Chunk
        | WebSocketResponse.Done
        | WebSocketResponse.Timestamps
        | WebSocketResponse.Error;

    interface Chunk extends WebSocketChunkResponse.Raw {
        type: "chunk";
    }

    interface Done extends WebSocketDoneResponse.Raw {
        type: "done";
    }

    interface Timestamps extends WebSocketTimestampsResponse.Raw {
        type: "timestamps";
    }

    interface Error extends WebSocketErrorResponse.Raw {
        type: "error";
    }
}
