/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";
import { WebSocketChunkResponse } from "./WebSocketChunkResponse";
import { WebSocketFlushDoneResponse } from "./WebSocketFlushDoneResponse";
import { WebSocketDoneResponse } from "./WebSocketDoneResponse";
import { WebSocketTimestampsResponse } from "./WebSocketTimestampsResponse";
import { WebSocketErrorResponse } from "./WebSocketErrorResponse";
import { WebSocketPhonemeTimestampsResponse } from "./WebSocketPhonemeTimestampsResponse";

export const WebSocketResponse: core.serialization.Schema<
    serializers.WebSocketResponse.Raw,
    Cartesia.WebSocketResponse
> = core.serialization
    .union("type", {
        chunk: WebSocketChunkResponse,
        flush_done: WebSocketFlushDoneResponse,
        done: WebSocketDoneResponse,
        timestamps: WebSocketTimestampsResponse,
        error: WebSocketErrorResponse,
        phoneme_timestamps: WebSocketPhonemeTimestampsResponse,
    })
    .transform<Cartesia.WebSocketResponse>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace WebSocketResponse {
    export type Raw =
        | WebSocketResponse.Chunk
        | WebSocketResponse.FlushDone
        | WebSocketResponse.Done
        | WebSocketResponse.Timestamps
        | WebSocketResponse.Error
        | WebSocketResponse.PhonemeTimestamps;

    export interface Chunk extends WebSocketChunkResponse.Raw {
        type: "chunk";
    }

    export interface FlushDone extends WebSocketFlushDoneResponse.Raw {
        type: "flush_done";
    }

    export interface Done extends WebSocketDoneResponse.Raw {
        type: "done";
    }

    export interface Timestamps extends WebSocketTimestampsResponse.Raw {
        type: "timestamps";
    }

    export interface Error extends WebSocketErrorResponse.Raw {
        type: "error";
    }

    export interface PhonemeTimestamps extends WebSocketPhonemeTimestampsResponse.Raw {
        type: "phoneme_timestamps";
    }
}
