/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";
import { WebSocketBaseResponse } from "./WebSocketBaseResponse";

export const WebSocketChunkResponse: core.serialization.ObjectSchema<
    serializers.WebSocketChunkResponse.Raw,
    Cartesia.WebSocketChunkResponse
> = core.serialization
    .object({
        data: core.serialization.string(),
        stepTime: core.serialization.property("step_time", core.serialization.number()),
    })
    .extend(WebSocketBaseResponse);

export declare namespace WebSocketChunkResponse {
    interface Raw extends WebSocketBaseResponse.Raw {
        data: string;
        step_time: number;
    }
}
