/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";
import { FlushId } from "./FlushId";
import { WebSocketBaseResponse } from "./WebSocketBaseResponse";

export const WebSocketFlushDoneResponse: core.serialization.ObjectSchema<
    serializers.WebSocketFlushDoneResponse.Raw,
    Cartesia.WebSocketFlushDoneResponse
> = core.serialization
    .object({
        flushId: core.serialization.property("flush_id", FlushId),
        flushDone: core.serialization.property("flush_done", core.serialization.boolean()),
    })
    .extend(WebSocketBaseResponse);

export declare namespace WebSocketFlushDoneResponse {
    export interface Raw extends WebSocketBaseResponse.Raw {
        flush_id: FlushId.Raw;
        flush_done: boolean;
    }
}
