/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";
import { WordTimestamps } from "./WordTimestamps";
import { WebSocketBaseResponse } from "./WebSocketBaseResponse";

export const WebSocketTimestampsResponse: core.serialization.ObjectSchema<
    serializers.WebSocketTimestampsResponse.Raw,
    Cartesia.WebSocketTimestampsResponse
> = core.serialization
    .object({
        wordTimestamps: core.serialization.property("word_timestamps", WordTimestamps.optional()),
    })
    .extend(WebSocketBaseResponse);

export declare namespace WebSocketTimestampsResponse {
    interface Raw extends WebSocketBaseResponse.Raw {
        word_timestamps?: WordTimestamps.Raw | null;
    }
}
