/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";

export const WordTimestamps: core.serialization.ObjectSchema<serializers.WordTimestamps.Raw, Cartesia.WordTimestamps> =
    core.serialization.object({
        words: core.serialization.list(core.serialization.string()),
        start: core.serialization.list(core.serialization.number()),
        end: core.serialization.list(core.serialization.number()),
    });

export declare namespace WordTimestamps {
    export interface Raw {
        words: string[];
        start: number[];
        end: number[];
    }
}
