/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { TokenGrant } from "./TokenGrant.js";

export const TokenRequest: core.serialization.ObjectSchema<serializers.TokenRequest.Raw, Cartesia.TokenRequest> =
    core.serialization.object({
        grants: TokenGrant.optional(),
        expiresIn: core.serialization.property("expires_in", core.serialization.number().optional()),
    });

export declare namespace TokenRequest {
    export interface Raw {
        grants?: TokenGrant.Raw | null;
        expires_in?: number | null;
    }
}
