/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";

export const TokenResponse: core.serialization.ObjectSchema<serializers.TokenResponse.Raw, Cartesia.TokenResponse> =
    core.serialization.object({
        token: core.serialization.string(),
    });

export declare namespace TokenResponse {
    export interface Raw {
        token: string;
    }
}
