/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CloneMode = "similarity" | "stability";

export const CloneMode = {
    Similarity: "similarity",
    Stability: "stability",
} as const;
