/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GenderPresentation = "masculine" | "feminine" | "gender_neutral";
export const GenderPresentation = {
    Masculine: "masculine",
    Feminine: "feminine",
    GenderNeutral: "gender_neutral",
} as const;
