/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index.js";

export interface GetVoicesResponse {
    /** The paginated list of Voices. */
    data: Cartesia.Voice[];
    /** Whether there are more Voices to fetch (using `starting_after=id`, where id is the ID of the last Voice in the current response). */
    hasMore: boolean;
    /** (Deprecated - use the id of the last Voice in the current response instead.) An ID that can be passed as `starting_after` to get the next page of Voices. */
    nextPage?: Cartesia.VoiceId;
}
