/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type LocalizeEnglishDialect = "au" | "in" | "so" | "uk" | "us";

export const LocalizeEnglishDialect = {
    Au: "au",
    In: "in",
    So: "so",
    Uk: "uk",
    Us: "us",
} as const;
