/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index";

/**
 * The dialect to localize to. Only supported for English (`en`).
 */
export type LocalizeDialect =
    /**
     * Only available when language is set to English (`en`).
     *  */
    Cartesia.LocalizeEnglishDialect;
