/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type LocalizePortugueseDialect = "br" | "eu";
export const LocalizePortugueseDialect = {
    Br: "br",
    Eu: "eu",
} as const;
