/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Target language to localize the voice to.
 *
 * Options: English (en), German (de), Spanish (es), French (fr), Japanese (ja), Portuguese (pt), Chinese (zh), Hindi (hi), Italian (it), Korean (ko), Dutch (nl), Polish (pl), Russian (ru), Swedish (sv), Turkish (tr).
 */
export type LocalizeTargetLanguage =
    | "en"
    | "de"
    | "es"
    | "fr"
    | "ja"
    | "pt"
    | "zh"
    | "hi"
    | "it"
    | "ko"
    | "nl"
    | "pl"
    | "ru"
    | "sv"
    | "tr";

export const LocalizeTargetLanguage = {
    En: "en",
    De: "de",
    Es: "es",
    Fr: "fr",
    Ja: "ja",
    Pt: "pt",
    Zh: "zh",
    Hi: "hi",
    It: "it",
    Ko: "ko",
    Nl: "nl",
    Pl: "pl",
    Ru: "ru",
    Sv: "sv",
    Tr: "tr",
} as const;
