/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index.js";

export interface LocalizeVoiceRequest {
    /** The ID of the voice to localize. */
    voiceId: string;
    /** The name of the new localized voice. */
    name: string;
    /** The description of the new localized voice. */
    description: string;
    language: Cartesia.LocalizeTargetLanguage;
    originalSpeakerGender: Cartesia.Gender;
    dialect?: Cartesia.LocalizeDialect;
}
