/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type LocalizeFrenchDialect = "eu" | "ca";
export const LocalizeFrenchDialect = {
    Eu: "eu",
    Ca: "ca",
} as const;
