/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index";

export type MixVoiceSpecifier = Cartesia.IdSpecifier | Cartesia.EmbeddingSpecifier;
