/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateVoiceRequest {
    /** The name of the voice. */
    name: string;
    /** The description of the voice. */
    description: string;
}
