/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index.js";

export interface UpdateVoiceRequest {
    /** The name of the voice. */
    name: string;
    /** The description of the voice. */
    description: string;
    gender?: Cartesia.GenderPresentation;
}
