/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index.js";

export interface Voice {
    id: Cartesia.VoiceId;
    /** Whether the current user is the owner of the voice. */
    isOwner: boolean;
    /** Whether the voice is publicly accessible. */
    isPublic: boolean;
    /** The name of the voice. */
    name: string;
    /** The description of the voice. */
    description: string;
    /** The gender of the voice, if specified. */
    gender?: Cartesia.GenderPresentation;
    /** The date and time the voice was created. */
    createdAt: Date;
    /** Whether the current user has starred the voice. Only included when `expand` includes `is_starred`. */
    isStarred?: boolean;
    language: Cartesia.SupportedLanguage;
}
