/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index";

export interface VoiceMetadata {
    id: Cartesia.VoiceId;
    /** The ID of the user who owns the voice. */
    userId: string;
    /** Whether the voice is publicly accessible. */
    isPublic: boolean;
    /** The name of the voice. */
    name: string;
    /** The description of the voice. */
    description: string;
    /** The date and time the voice was created. */
    createdAt: Date;
    language: Cartesia.SupportedLanguage;
}
