/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The weight of the voice or embedding in the mix. If weights do not sum to 1, they will be normalized.
 */
export type Weight = number;
