/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type OutputFormatContainer = "raw" | "wav" | "mp3";
export const OutputFormatContainer = {
    Raw: "raw",
    Wav: "wav",
    Mp3: "mp3",
} as const;
