/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index.js";

export type StreamingResponse =
    | Cartesia.StreamingResponse.Chunk
    | Cartesia.StreamingResponse.Done
    | Cartesia.StreamingResponse.Error_;

export namespace StreamingResponse {
    export interface Chunk extends Cartesia.WebSocketChunkResponse {
        type: "chunk";
    }

    export interface Done extends Cartesia.WebSocketDoneResponse {
        type: "done";
    }

    export interface Error_ extends Cartesia.WebSocketErrorResponse {
        type: "error";
    }
}
