/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         agentId: "agent_id"
 *     }
 */
export interface ListCallsRequest {
    /** The ID of the agent. */
    agentId: string;
    /** The fields to expand in the response. Currently, the only supported value is `transcript`. */
    expand?: string;
    /** (Pagination option)The ID of the call to start after. */
    startingAfter?: string;
    /** (Pagination option) The ID of the call to end before. */
    endingBefore?: string;
    /** (Pagination option) The number of calls to return per page, ranging between 1 and 100. */
    limit?: number;
}
