/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ListMetricsRequest {
    /** (Pagination option) The ID of the last Metric in the current response as a cursor for the next page of results. */
    startingAfter?: string;
    /** (Pagination option) The number of metrics to return per page, ranging between 1 and 100. The default page limit is 10. */
    limit?: number;
}
