/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ListMetricResultsRequest {
    /** The ID of the agent. */
    agentId?: string;
    /** The ID of the deployment. */
    deploymentId?: string;
    /** The ID of the metric. */
    metricId?: string;
    /** The ID of the call. */
    callId?: string;
    /** A cursor to use in pagination. `starting_after` is a metric result ID that defines your place in the list. For example, if you make a /metrics/results request and receive 100 objects, ending with `metric_result_abc123`, your subsequent call can include `starting_after=metric_result_abc123` to fetch the next page of the list. */
    startingAfter?: string;
    /** A cursor to use in pagination. `ending_before` is a metric result ID that defines your place in the list. For example, if you make a /metrics/results request and receive 100 objects, starting with `metric_result_abc123`, your subsequent call can include `ending_before=metric_result_abc123` to fetch the previous page of the list. */
    endingBefore?: string;
    /** The number of metric results to return per page, ranging between 1 and 100. */
    limit?: number;
}
