/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index";

export interface CancelContextRequest {
    /** The ID of the context to cancel. */
    context_id: Cartesia.ContextId;
    /** Whether to cancel the context, so that no more messages are generated for that context. */
    cancel: true;
}
