/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index";

export interface Controls {
    speed: Cartesia.Speed;
    emotion: Cartesia.Emotion;
}
