/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An array of emotion:level tags.
 *
 * Supported emotions are: anger, positivity, surprise, sadness, and curiosity.
 *
 * Supported levels are: lowest, low, (omit), high, highest.
 */
export type Emotion =
    | "anger:lowest"
    | "anger:low"
    | "anger"
    | "anger:high"
    | "anger:highest"
    | "positivity:lowest"
    | "positivity:low"
    | "positivity"
    | "positivity:high"
    | "positivity:highest"
    | "surprise:lowest"
    | "surprise:low"
    | "surprise"
    | "surprise:high"
    | "surprise:highest"
    | "sadness:lowest"
    | "sadness:low"
    | "sadness"
    | "sadness:high"
    | "sadness:highest"
    | "curiosity:lowest"
    | "curiosity:low"
    | "curiosity"
    | "curiosity:high"
    | "curiosity:highest";
export const Emotion = {
    AngerLowest: "anger:lowest",
    AngerLow: "anger:low",
    Anger: "anger",
    AngerHigh: "anger:high",
    AngerHighest: "anger:highest",
    PositivityLowest: "positivity:lowest",
    PositivityLow: "positivity:low",
    Positivity: "positivity",
    PositivityHigh: "positivity:high",
    PositivityHighest: "positivity:highest",
    SurpriseLowest: "surprise:lowest",
    SurpriseLow: "surprise:low",
    Surprise: "surprise",
    SurpriseHigh: "surprise:high",
    SurpriseHighest: "surprise:highest",
    SadnessLowest: "sadness:lowest",
    SadnessLow: "sadness:low",
    Sadness: "sadness",
    SadnessHigh: "sadness:high",
    SadnessHighest: "sadness:highest",
    CuriosityLowest: "curiosity:lowest",
    CuriosityLow: "curiosity:low",
    Curiosity: "curiosity",
    CuriosityHigh: "curiosity:high",
    CuriosityHighest: "curiosity:highest",
} as const;
