/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A unique identifier for the flush. You can use any unique identifier, like a UUID or human ID.
 *
 * Some customers use unique identifiers from their own systems (such as conversation IDs) as flush IDs.
 */
export type FlushId = number;
