/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An identifier corresponding to the number of flush commands that have been sent for this context. Starts at 1.
 *
 * This can be used to map chunks of audio to certain transcript submissions.
 */
export type FlushId = number;
