/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index";

/**
 * Configure the various attributes of the generated speech. These controls only for `sonic-3` and have no effect on earlier models.
 */
export interface GenerationConfig {
    /** Adjust the volume of the generated speech between 0.5x and 2.0x the original volume (default is 1.0x). Valid values are between 0.5 and 2.0 inclusive. */
    volume?: number;
    /** Adjust the speed of the generated speech between 0.6x and 1.5x the original speed (default is 1.0x). Valid values are between 0.6 and 1.5 inclusive. */
    speed?: number;
    /** Guide the emotion of the generated speech. */
    emotion?: Cartesia.Emotion;
}
