/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * > This feature is experimental and may not work for all voices.
 *
 * Speed setting for the model. Defaults to `normal`.
 *
 * Influences the speed of the generated speech. Faster speeds may reduce hallucination rate.
 */
export type ModelSpeed = "slow" | "normal" | "fast";
export const ModelSpeed = {
    Slow: "slow",
    Normal: "normal",
    Fast: "fast",
} as const;
