/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Mp3OutputFormat {
    sampleRate: number;
    /** The bit rate of the audio in bits per second. Supported bit rates are 32000, 64000, 96000, 128000, 192000. */
    bitRate: number;
}
