/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type NaturalSpecifier = "slowest" | "slow" | "normal" | "fast" | "fastest";
export const NaturalSpecifier = {
    Slowest: "slowest",
    Slow: "slow",
    Normal: "normal",
    Fast: "fast",
    Fastest: "fastest",
} as const;
