/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index";

export interface RawBytesOutputFormat extends Cartesia.RawOutputFormat {
    /**
     * The loudness of the audio in LUFS.
     * Supports values between -14 (loudest) and -24 (quietest).
     */
    loudness?: number;
}
