/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type RawEncoding = "pcm_f32le" | "pcm_s16le" | "pcm_mulaw" | "pcm_alaw";
export const RawEncoding = {
    PcmF32Le: "pcm_f32le",
    PcmS16Le: "pcm_s16le",
    PcmMulaw: "pcm_mulaw",
    PcmAlaw: "pcm_alaw",
} as const;
