/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index";

export interface SseOutputFormat {
    container: "raw";
    encoding: Cartesia.RawEncoding;
    /** The sample rate of the audio in Hz. Supported sample rates are 8000, 16000, 22050, 24000, 44100, 48000. */
    sampleRate: number;
}
