/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index";

export type SseOutputFormat = Cartesia.SseOutputFormat.Raw | Cartesia.SseOutputFormat.Wav;

export declare namespace SseOutputFormat {
    interface Raw extends Cartesia.RawOutputFormat {
        container: "raw";
    }

    interface Wav extends Cartesia.WavOutputFormat {
        container: "wav";
    }
}
