/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index";

export interface TtsRequestIdSpecifier {
    id: Cartesia.VoiceId;
    __experimental_controls?: Cartesia.Controls;
}
