/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index";

export interface TtsRequestEmbeddingSpecifier {
    embedding: Cartesia.Embedding;
    __experimental_controls?: Cartesia.Controls;
}
