/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index";

export type TtsRequestVoiceSpecifier =
    | Cartesia.TtsRequestVoiceSpecifier.Id
    | Cartesia.TtsRequestVoiceSpecifier.Embedding;

export declare namespace TtsRequestVoiceSpecifier {
    interface Id extends Cartesia.TtsRequestIdSpecifier {
        mode: "id";
    }

    interface Embedding extends Cartesia.TtsRequestEmbeddingSpecifier {
        mode: "embedding";
    }
}
