/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index";

export interface WebSocketTtsOutput {
    wordTimestamps?: Cartesia.WordTimestamps;
    audio?: unknown;
    contextId?: Cartesia.ContextId;
}
