/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index";

export interface WebSocketBaseResponse {
    context_id?: Cartesia.ContextId;
    status_code: number;
    done: boolean;
}
