/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index";

export type WebSocketResponse =
    | Cartesia.WebSocketResponse.Chunk
    | Cartesia.WebSocketResponse.Done
    | Cartesia.WebSocketResponse.Timestamps
    | Cartesia.WebSocketResponse.Error_;

export declare namespace WebSocketResponse {
    interface Chunk extends Cartesia.WebSocketChunkResponse {
        type: "chunk";
    }

    interface Done extends Cartesia.WebSocketDoneResponse {
        type: "done";
    }

    interface Timestamps extends Cartesia.WebSocketTimestampsResponse {
        type: "timestamps";
    }

    interface Error_ extends Cartesia.WebSocketErrorResponse {
        type: "error";
    }
}
