/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index.js";

export interface WebSocketTtsOutput {
    wordTimestamps?: Cartesia.WordTimestamps;
    phonemeTimestamps?: Cartesia.PhonemeTimestamps;
    audio?: unknown;
    contextId?: Cartesia.ContextId;
    flushId?: Cartesia.FlushId;
    flushDone?: boolean;
}
