/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index";

export interface WebSocketBaseResponse {
    contextId?: Cartesia.ContextId;
    statusCode: number;
    done: boolean;
}
