/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index.js";

export interface WebSocketRawOutputFormat {
    container: "raw";
    encoding: Cartesia.RawEncoding;
    sampleRate: number;
}
