/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { PronunciationDictItem } from "./PronunciationDictItem.js";

export const CreatePronunciationDictRequest: core.serialization.ObjectSchema<
    serializers.CreatePronunciationDictRequest.Raw,
    Cartesia.CreatePronunciationDictRequest
> = core.serialization.object({
    name: core.serialization.string(),
    items: core.serialization.list(PronunciationDictItem).optional(),
});

export declare namespace CreatePronunciationDictRequest {
    export interface Raw {
        name: string;
        items?: PronunciationDictItem.Raw[] | null;
    }
}
