/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { PronunciationDict } from "./PronunciationDict.js";

export const PaginatedPronunciationDicts: core.serialization.ObjectSchema<
    serializers.PaginatedPronunciationDicts.Raw,
    Cartesia.PaginatedPronunciationDicts
> = core.serialization.object({
    data: core.serialization.list(PronunciationDict),
    hasMore: core.serialization.property("has_more", core.serialization.boolean()),
});

export declare namespace PaginatedPronunciationDicts {
    export interface Raw {
        data: PronunciationDict.Raw[];
        has_more: boolean;
    }
}
