/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const PronunciationDictItem: core.serialization.ObjectSchema<
    serializers.PronunciationDictItem.Raw,
    Cartesia.PronunciationDictItem
> = core.serialization.object({
    text: core.serialization.string(),
    alias: core.serialization.string(),
});

export declare namespace PronunciationDictItem {
    export interface Raw {
        text: string;
        alias: string;
    }
}
