/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { PronunciationDictItem } from "./PronunciationDictItem.js";

export const PronunciationDict: core.serialization.ObjectSchema<
    serializers.PronunciationDict.Raw,
    Cartesia.PronunciationDict
> = core.serialization.object({
    id: core.serialization.string(),
    name: core.serialization.string(),
    ownerId: core.serialization.property("owner_id", core.serialization.string()),
    pinned: core.serialization.boolean(),
    items: core.serialization.list(PronunciationDictItem),
    createdAt: core.serialization.property("created_at", core.serialization.string()),
});

export declare namespace PronunciationDict {
    export interface Raw {
        id: string;
        name: string;
        owner_id: string;
        pinned: boolean;
        items: PronunciationDictItem.Raw[];
        created_at: string;
    }
}
