/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { PronunciationDictItem } from "./PronunciationDictItem.js";

export const UpdatePronunciationDictRequest: core.serialization.ObjectSchema<
    serializers.UpdatePronunciationDictRequest.Raw,
    Cartesia.UpdatePronunciationDictRequest
> = core.serialization.object({
    name: core.serialization.string().optional(),
    items: core.serialization.list(PronunciationDictItem).optional(),
});

export declare namespace UpdatePronunciationDictRequest {
    export interface Raw {
        name?: string | null;
        items?: PronunciationDictItem.Raw[] | null;
    }
}
