/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { AgentTranscript } from "./AgentTranscript.js";
import { TelephonyParams } from "./TelephonyParams.js";
import { AgentCallStatus } from "./AgentCallStatus.js";

export const AgentCall: core.serialization.ObjectSchema<serializers.AgentCall.Raw, Cartesia.AgentCall> =
    core.serialization.object({
        id: core.serialization.string(),
        agentId: core.serialization.property("agent_id", core.serialization.string()),
        startTime: core.serialization.property("start_time", core.serialization.date().optional()),
        endTime: core.serialization.property("end_time", core.serialization.date().optional()),
        transcript: core.serialization.list(AgentTranscript).optional(),
        telephonyParams: core.serialization.property("telephony_params", TelephonyParams.optional()),
        summary: core.serialization.string().optional(),
        status: AgentCallStatus,
        errorMessage: core.serialization.property("error_message", core.serialization.string().optional()),
        deploymentId: core.serialization.property("deployment_id", core.serialization.string().optional()),
    });

export declare namespace AgentCall {
    export interface Raw {
        id: string;
        agent_id: string;
        start_time?: string | null;
        end_time?: string | null;
        transcript?: AgentTranscript.Raw[] | null;
        telephony_params?: TelephonyParams.Raw | null;
        summary?: string | null;
        status: AgentCallStatus.Raw;
        error_message?: string | null;
        deployment_id?: string | null;
    }
}
