/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const AgentCallStatus: core.serialization.Schema<serializers.AgentCallStatus.Raw, Cartesia.AgentCallStatus> =
    core.serialization.enum_(["active", "completed", "failed", "cancelled"]);

export declare namespace AgentCallStatus {
    export type Raw = "active" | "completed" | "failed" | "cancelled";
}
