/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { VoiceId } from "../../voices/types/VoiceId.js";
import { GitRepository } from "./GitRepository.js";
import { PhoneNumberSummary } from "./PhoneNumberSummary.js";

export const AgentSummary: core.serialization.ObjectSchema<serializers.AgentSummary.Raw, Cartesia.AgentSummary> =
    core.serialization.object({
        id: core.serialization.string(),
        name: core.serialization.string(),
        description: core.serialization.string().optional(),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
        updatedAt: core.serialization.property("updated_at", core.serialization.date()),
        ttsVoice: core.serialization.property("tts_voice", VoiceId),
        ttsLanguage: core.serialization.property("tts_language", core.serialization.string()),
        webhookId: core.serialization.property("webhook_id", core.serialization.string().optional()),
        deletedAt: core.serialization.property("deleted_at", core.serialization.date().optional()),
        gitRepository: core.serialization.property("git_repository", GitRepository.optional()),
        gitDeployBranch: core.serialization.property("git_deploy_branch", core.serialization.string().optional()),
        phoneNumbers: core.serialization.property(
            "phone_numbers",
            core.serialization.list(PhoneNumberSummary).optional(),
        ),
        hasTextToAgentRun: core.serialization.property("has_text_to_agent_run", core.serialization.boolean()),
        deploymentCount: core.serialization.property("deployment_count", core.serialization.number()),
    });

export declare namespace AgentSummary {
    export interface Raw {
        id: string;
        name: string;
        description?: string | null;
        created_at: string;
        updated_at: string;
        tts_voice: VoiceId.Raw;
        tts_language: string;
        webhook_id?: string | null;
        deleted_at?: string | null;
        git_repository?: GitRepository.Raw | null;
        git_deploy_branch?: string | null;
        phone_numbers?: PhoneNumberSummary.Raw[] | null;
        has_text_to_agent_run: boolean;
        deployment_count: number;
    }
}
