/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const CreateMetricRequest: core.serialization.ObjectSchema<
    serializers.CreateMetricRequest.Raw,
    Cartesia.CreateMetricRequest
> = core.serialization.object({
    name: core.serialization.string(),
    displayName: core.serialization.property("display_name", core.serialization.string().optional()),
    prompt: core.serialization.string(),
});

export declare namespace CreateMetricRequest {
    export interface Raw {
        name: string;
        display_name?: string | null;
        prompt: string;
    }
}
