/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { AgentSummary } from "./AgentSummary.js";

export const GetAgentsResponse: core.serialization.ObjectSchema<
    serializers.GetAgentsResponse.Raw,
    Cartesia.GetAgentsResponse
> = core.serialization.object({
    summaries: core.serialization.list(AgentSummary),
});

export declare namespace GetAgentsResponse {
    export interface Raw {
        summaries: AgentSummary.Raw[];
    }
}
