/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { AgentCall } from "./AgentCall.js";

export const GetCallsResponse: core.serialization.ObjectSchema<
    serializers.GetCallsResponse.Raw,
    Cartesia.GetCallsResponse
> = core.serialization.object({
    data: core.serialization.list(AgentCall),
    nextPage: core.serialization.property("next_page", core.serialization.string().optional()),
});

export declare namespace GetCallsResponse {
    export interface Raw {
        data: AgentCall.Raw[];
        next_page?: string | null;
    }
}
