/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { AgentTemplate } from "./AgentTemplate.js";

export const GetTemplatesResponse: core.serialization.ObjectSchema<
    serializers.GetTemplatesResponse.Raw,
    Cartesia.GetTemplatesResponse
> = core.serialization.object({
    templates: core.serialization.list(AgentTemplate),
});

export declare namespace GetTemplatesResponse {
    export interface Raw {
        templates: AgentTemplate.Raw[];
    }
}
