/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { Metric } from "./Metric.js";

export const ListMetricsResponse: core.serialization.ObjectSchema<
    serializers.ListMetricsResponse.Raw,
    Cartesia.ListMetricsResponse
> = core.serialization.object({
    data: core.serialization.list(Metric),
    hasMore: core.serialization.property("has_more", core.serialization.boolean()),
    nextPage: core.serialization.property("next_page", core.serialization.string().optional()),
});

export declare namespace ListMetricsResponse {
    export interface Raw {
        data: Metric.Raw[];
        has_more: boolean;
        next_page?: string | null;
    }
}
