/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { MetricResult } from "./MetricResult.js";

export const ListMetricResultsResponse: core.serialization.ObjectSchema<
    serializers.ListMetricResultsResponse.Raw,
    Cartesia.ListMetricResultsResponse
> = core.serialization.object({
    data: core.serialization.list(MetricResult),
    hasMore: core.serialization.property("has_more", core.serialization.boolean()),
    nextPage: core.serialization.property("next_page", core.serialization.string().optional()),
});

export declare namespace ListMetricResultsResponse {
    export interface Raw {
        data: MetricResult.Raw[];
        has_more: boolean;
        next_page?: string | null;
    }
}
