/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const LogMetric: core.serialization.ObjectSchema<serializers.LogMetric.Raw, Cartesia.LogMetric> =
    core.serialization.object({
        name: core.serialization.string(),
        value: core.serialization.number(),
        timestamp: core.serialization.number(),
    });

export declare namespace LogMetric {
    export interface Raw {
        name: string;
        value: number;
        timestamp: number;
    }
}
