/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const Metric: core.serialization.ObjectSchema<serializers.Metric.Raw, Cartesia.Metric> =
    core.serialization.object({
        id: core.serialization.string(),
        name: core.serialization.string(),
        displayName: core.serialization.property("display_name", core.serialization.string().optional()),
        prompt: core.serialization.string(),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
    });

export declare namespace Metric {
    export interface Raw {
        id: string;
        name: string;
        display_name?: string | null;
        prompt: string;
        created_at: string;
    }
}
