/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const PhoneNumberSummary: core.serialization.ObjectSchema<
    serializers.PhoneNumberSummary.Raw,
    Cartesia.PhoneNumberSummary
> = core.serialization.object({
    id: core.serialization.string(),
    number: core.serialization.string(),
});

export declare namespace PhoneNumberSummary {
    export interface Raw {
        id: string;
        number: string;
    }
}
