/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const TextChunk: core.serialization.ObjectSchema<serializers.TextChunk.Raw, Cartesia.TextChunk> =
    core.serialization.object({
        text: core.serialization.string(),
        startTimestamp: core.serialization.property("start_timestamp", core.serialization.number()),
    });

export declare namespace TextChunk {
    export interface Raw {
        text: string;
        start_timestamp: number;
    }
}
