/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const ToolCall: core.serialization.ObjectSchema<serializers.ToolCall.Raw, Cartesia.ToolCall> =
    core.serialization.object({
        id: core.serialization.string(),
        name: core.serialization.string(),
        arguments: core.serialization.record(core.serialization.string(), core.serialization.string()),
    });

export declare namespace ToolCall {
    export interface Raw {
        id: string;
        name: string;
        arguments: Record<string, string>;
    }
}
