/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";

export const Embedding: core.serialization.Schema<serializers.Embedding.Raw, Cartesia.Embedding> =
    core.serialization.list(core.serialization.number());

export declare namespace Embedding {
    export type Raw = number[];
}
