/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface CloneFromClipRequest {
    /**
     * Whether to enhance the clip to improve its quality before cloning. Useful if the clip is low quality.
     *
     */
    enhance: boolean;
}
