/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../../index";

/**
 * @example
 *     {
 *         name: "A high-stability cloned voice",
 *         description: "Copied from Cartesia docs",
 *         mode: "stability",
 *         language: "en"
 *     }
 *
 * @example
 *     {
 *         name: "A high-similarity cloned voice",
 *         description: "Copied from Cartesia docs",
 *         mode: "similarity",
 *         language: "en"
 *     }
 */
export interface CloneVoiceRequest {
    /** The name of the voice. */
    name: string;
    /** A description for the voice. */
    description?: string;
    /** The language of the voice. */
    language: Cartesia.SupportedLanguage;
    /** Tradeoff between similarity and stability. Similarity clones sound more like the source clip, but may reproduce background noise. Stability clones always sound like a studio recording, but may not sound as similar to the source clip. */
    mode: Cartesia.CloneMode;
    /** Whether to apply AI enhancements to the clip to reduce background noise. This leads to cleaner generated speech at the cost of reduced similarity to the source clip. */
    enhance?: boolean;
    /** Optional base voice ID that the cloned voice is derived from. */
    baseVoiceId?: Cartesia.VoiceId;
}
