/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../../index";

/**
 * @example
 *     {
 *         name: "A high-stability cloned voice",
 *         description: "Copied from Cartesia docs",
 *         mode: "stability",
 *         language: "en",
 *         enhance: true
 *     }
 *
 * @example
 *     {
 *         name: "A high-similarity cloned voice",
 *         description: "Copied from Cartesia docs",
 *         mode: "similarity",
 *         language: "en",
 *         transcript: "A transcript of the words spoken in the audio clip.",
 *         enhance: false
 *     }
 */
export interface CloneVoiceRequest {
    /**
     * The name of the voice.
     *
     */
    name: string;
    /**
     * A description for the voice.
     *
     */
    description?: string;
    /**
     * The language of the voice.
     *
     */
    language: Cartesia.SupportedLanguage;
    /**
     * Tradeoff between similarity and stability. Similarity clones sound more like the source clip, but may reproduce background noise. Stability clones always sound like a studio recording, but may not sound as similar to the source clip.
     *
     */
    mode: Cartesia.CloneMode;
    /**
     * Whether to enhance the clip to improve its quality before cloning. Useful if the clip has background noise.
     *
     */
    enhance?: boolean;
    /**
     * Optional transcript of the words spoken in the audio clip. Only used for similarity mode.
     *
     */
    transcript?: string;
}
