/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../../index.js";

/**
 * @example
 *     {
 *         gender: null
 *     }
 */
export interface GetVoicesRequest {
    /** The number of Voices to return per page, ranging between 1 and 100. */
    limit?: number;
    /**
     * A cursor to use in pagination. `starting_after` is a Voice ID that defines your
     * place in the list. For example, if you make a /voices request and receive 100
     * objects, ending with `voice_abc123`, your subsequent call can include
     * `starting_after=voice_abc123` to fetch the next page of the list.
     */
    startingAfter?: string;
    /**
     * A cursor to use in pagination. `ending_before` is a Voice ID that defines your
     * place in the list. For example, if you make a /voices request and receive 100
     * objects, starting with `voice_abc123`, your subsequent call can include
     * `ending_before=voice_abc123` to fetch the previous page of the list.
     */
    endingBefore?: string;
    /** Whether to only return voices owned by the current user. */
    isOwner?: boolean;
    /** Whether to only return starred voices. */
    isStarred?: boolean;
    /** The gender presentation of the voices to return. */
    gender: Cartesia.GenderPresentation | null;
    /** Additional fields to include in the response. */
    expand?: Cartesia.VoiceExpandOptions[];
}
