/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Acknowledgment message sent in response to a `done` command, indicating that the session is complete and the WebSocket will close.
 */
export interface DoneMessage {
    /** Unique identifier for this transcription session. */
    requestId: string;
}
