/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ErrorMessage {
    /** The request ID associated with the error, if applicable. */
    requestId?: string;
    /** Human-readable error message describing what went wrong. */
    message: string;
}
