/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index.js";

/**
 * The server sends transcription results, control messages, or error messages. Each message has a `type` field to distinguish between different message types.
 */
export type StreamingTranscriptionResponse =
    | Cartesia.StreamingTranscriptionResponse.Transcript
    | Cartesia.StreamingTranscriptionResponse.FlushDone
    | Cartesia.StreamingTranscriptionResponse.Done
    | Cartesia.StreamingTranscriptionResponse.Error_;

export namespace StreamingTranscriptionResponse {
    export interface Transcript extends Cartesia.TranscriptMessage {
        type: "transcript";
    }

    export interface FlushDone extends Cartesia.FlushDoneMessage {
        type: "flush_done";
    }

    export interface Done extends Cartesia.DoneMessage {
        type: "done";
    }

    export interface Error_ extends Cartesia.ErrorMessage {
        type: "error";
    }
}
