/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The encoding format for audio data sent to the STT WebSocket.
 *
 * Currently supported:
 * - `pcm_s16le` - 16-bit signed integer PCM, little-endian
 *
 * Support for other formats will be added in the future.
 */
export type SttEncoding = "pcm_s16le";
export const SttEncoding = {
    PcmS16Le: "pcm_s16le",
} as const;
