/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index.js";

export interface TranscriptMessage {
    /** Unique identifier for this transcription session. */
    requestId: string;
    /**
     * The transcribed text. May be partial or final depending on is_final.
     *
     * **Note**: Text may be empty in initial responses while the system accumulates sufficient audio for transcription. This is normal behavior - wait for responses with non-empty text or monitor is_final for completion status.
     */
    text: string;
    /** Whether this is a final transcription result or an interim result. */
    isFinal: boolean;
    /** The duration of the audio transcribed so far, in seconds. */
    duration?: number;
    /** The specified language of the input audio. */
    language?: string;
    /** Word-level timestamps showing the start and end time of each word in seconds. Always included in streaming responses. */
    words?: Cartesia.TranscriptionWord[];
}
