/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index";

export interface TranscriptionResponse {
    /** The transcribed text. */
    text: string;
    /** The detected or specified language of the input audio. */
    language?: string;
    /** The duration of the input audio in seconds. */
    duration?: number;
}
