/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Request to create a new fine-tune
 */
export interface CreateFineTuneRequest {
    /** Name for the new fine-tune */
    name: string;
    /** Description for the fine-tune */
    description: string;
    /** Language code for the fine-tune */
    language: string;
    /** Base model ID to fine-tune from */
    modelId: string;
    /** Dataset ID containing training files */
    dataset: string;
}
