/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index.js";

/**
 * Information about a fine-tune
 */
export interface FineTune {
    /** Unique identifier for the fine-tune */
    id: string;
    /** Name of the fine-tune */
    name: string;
    /** Description of the fine-tune */
    description: string;
    /** Language code of the fine-tune */
    language: string;
    /** Base model identifier to fine-tune from */
    modelId: string;
    /** ID of the dataset used for fine-tuning */
    dataset: string;
    /** Current status of the fine-tune */
    status: Cartesia.FineTuneStatus;
}
