/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index.js";

/**
 * Paginated list of voices created from a fine-tune
 */
export interface PaginatedVoices {
    /** List of voice objects */
    data: Cartesia.Voice[];
    /** Whether there are more voices available */
    hasMore: boolean;
}
