/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index.js";

/**
 * Paginated list of fine-tunes
 */
export interface PaginatedFineTunes {
    /** List of fine-tune objects */
    data: Cartesia.FineTune[];
    /** Whether there are more fine-tunes available */
    hasMore: boolean;
}
