/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";

export const DoneMessage: core.serialization.ObjectSchema<serializers.DoneMessage.Raw, Cartesia.DoneMessage> =
    core.serialization.object({
        requestId: core.serialization.property("request_id", core.serialization.string()),
    });

export declare namespace DoneMessage {
    export interface Raw {
        request_id: string;
    }
}
