/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const ErrorMessage: core.serialization.ObjectSchema<serializers.ErrorMessage.Raw, Cartesia.ErrorMessage> =
    core.serialization.object({
        requestId: core.serialization.property("request_id", core.serialization.string().optional()),
        message: core.serialization.string(),
    });

export declare namespace ErrorMessage {
    export interface Raw {
        request_id?: string | null;
        message: string;
    }
}
