/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";

export const FlushDoneMessage: core.serialization.ObjectSchema<
    serializers.FlushDoneMessage.Raw,
    Cartesia.FlushDoneMessage
> = core.serialization.object({
    requestId: core.serialization.property("request_id", core.serialization.string()),
});

export declare namespace FlushDoneMessage {
    export interface Raw {
        request_id: string;
    }
}
