/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";

export const SttEncoding: core.serialization.Schema<serializers.SttEncoding.Raw, Cartesia.SttEncoding> =
    core.serialization.enum_(["pcm_s16le"]);

export declare namespace SttEncoding {
    export type Raw = "pcm_s16le";
}
