/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";

export const TimestampGranularity: core.serialization.Schema<
    serializers.TimestampGranularity.Raw,
    Cartesia.TimestampGranularity
> = core.serialization.enum_(["word"]);

export declare namespace TimestampGranularity {
    export type Raw = "word";
}
