/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";
import { TranscriptionWord } from "./TranscriptionWord";

export const TranscriptionResponse: core.serialization.ObjectSchema<
    serializers.TranscriptionResponse.Raw,
    Cartesia.TranscriptionResponse
> = core.serialization.object({
    text: core.serialization.string(),
    language: core.serialization.string().optional(),
    duration: core.serialization.number().optional(),
    words: core.serialization.list(TranscriptionWord).optional(),
});

export declare namespace TranscriptionResponse {
    export interface Raw {
        text: string;
        language?: string | null;
        duration?: number | null;
        words?: TranscriptionWord.Raw[] | null;
    }
}
