/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index.js";

/**
 * Request to create a new pronunciation dictionary
 */
export interface CreatePronunciationDictRequest {
    /** Name for the new pronunciation dictionary */
    name: string;
    /** Optional initial list of pronunciation mappings */
    items?: Cartesia.PronunciationDictItem[];
}
