/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index.js";

/**
 * Request to update an existing pronunciation dictionary
 */
export interface UpdatePronunciationDictRequest {
    /** New name for the pronunciation dictionary */
    name?: string;
    /** Updated list of pronunciation mappings */
    items?: Cartesia.PronunciationDictItem[];
}
