/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const FineTuneStatus: core.serialization.Schema<serializers.FineTuneStatus.Raw, Cartesia.FineTuneStatus> =
    core.serialization.enum_(["created", "training", "completed", "failed"]);

export declare namespace FineTuneStatus {
    export type Raw = "created" | "training" | "completed" | "failed";
}
