/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { FineTuneStatus } from "./FineTuneStatus.js";

export const FineTune: core.serialization.ObjectSchema<serializers.FineTune.Raw, Cartesia.FineTune> =
    core.serialization.object({
        id: core.serialization.string(),
        name: core.serialization.string(),
        description: core.serialization.string(),
        language: core.serialization.string(),
        modelId: core.serialization.property("model_id", core.serialization.string()),
        dataset: core.serialization.string(),
        status: FineTuneStatus,
    });

export declare namespace FineTune {
    export interface Raw {
        id: string;
        name: string;
        description: string;
        language: string;
        model_id: string;
        dataset: string;
        status: FineTuneStatus.Raw;
    }
}
