/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { FineTune } from "./FineTune.js";

export const PaginatedFineTunes: core.serialization.ObjectSchema<
    serializers.PaginatedFineTunes.Raw,
    Cartesia.PaginatedFineTunes
> = core.serialization.object({
    data: core.serialization.list(FineTune),
    hasMore: core.serialization.property("has_more", core.serialization.boolean()),
});

export declare namespace PaginatedFineTunes {
    export interface Raw {
        data: FineTune.Raw[];
        has_more: boolean;
    }
}
