/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index.js";

export interface AgentCall {
    /** The unique identifier for the agent call. */
    id: string;
    /** The identifier of the agent associated with the call. */
    agentId: string;
    /** The start time of the agent call. */
    startTime?: Date;
    /** The end time of the agent call. */
    endTime?: Date;
    /** The transcript of the agent call. */
    transcript?: Cartesia.AgentTranscript[];
    /** The telephony parameters associated with the call when the call is made via phone. */
    telephonyParams?: Cartesia.TelephonyParams;
    /** A summary of the agent call. This is a brief summary of the call that is generated by Cartesia. */
    summary?: string;
    /** The status of the agent call. */
    status: Cartesia.AgentCallStatus;
    /** The error message, if any, associated with the call. */
    errorMessage?: string;
    /** The deployment identifier associated with the call. */
    deploymentId?: string;
}
