/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index.js";

/**
 * A summary of essential information about an agent.
 */
export interface AgentSummary {
    /** The ID of the agent. */
    id: string;
    /** The unique name of the agent, which can be used to identify the agent in the CLI. */
    name: string;
    /** A brief description of the agent. */
    description?: string;
    /** The date and time when the agent was created. */
    createdAt: Date;
    /** The date and time when the agent was last updated. */
    updatedAt: Date;
    /** The text-to-speech voice used by the agent. */
    ttsVoice: Cartesia.VoiceId;
    /** The language used for text-to-speech by the agent. */
    ttsLanguage: string;
    /** The identifier for the webhook associated with the agent. Add or customize a webhook to your agent to receive events when calls are made to your agent via the Playground. */
    webhookId?: string;
    /** The date and time when the agent was deleted, if applicable. */
    deletedAt?: Date;
    /** The Git repository associated with the agent. */
    gitRepository?: Cartesia.GitRepository;
    /** The branch of the Git repository used for deployment. */
    gitDeployBranch?: string;
    /** The phone numbers associated with the agent. Currently, you can only have one phone number per agent. */
    phoneNumbers?: Cartesia.PhoneNumberSummary[];
    /** Whether the agent has a text-to-agent run. */
    hasTextToAgentRun: boolean;
    /** The number of deployments associated with the agent. */
    deploymentCount: number;
}
