/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of an agent metric result. `failed` indicates that the metric result was not computed or parsed properly.
 */
export type AgentMetricResultStatus = "completed" | "failed";
export const AgentMetricResultStatus = {
    Completed: "completed",
    Failed: "failed",
} as const;
