/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AgentTemplate {
    /** The ID of the agent template. */
    id: string;
    /** The name of the agent template. */
    name: string;
    /** The description of the agent template. */
    description?: string;
    /** The URL of the Git repository associated with the agent template. */
    repoUrl: string;
    /** The root directory of the agent template. */
    rootDir: string;
    /** The required environment variables for the agent template. */
    requiredEnvVars?: string[];
    /** The dependencies of the agent template. */
    dependencies?: string[];
    /** The ID of the owner of the agent template. */
    ownerId: string;
    /** The UTC timestamp when the agent template was created. */
    createdAt: Date;
    /** The UTC timestamp when the agent template was last updated. */
    updatedAt: Date;
}
