/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateMetricRequest {
    /** The name of the metric. This must be a unique name that only allows lower case letters, numbers, and the characters _, -, and . */
    name: string;
    /** The display name of the metric. */
    displayName?: string;
    /** The prompt associated with the metric, detailing the task and evaluation criteria. */
    prompt: string;
}
