/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index.js";

export interface GetAgentsResponse {
    /** The summaries of the agents. */
    summaries: Cartesia.AgentSummary[];
}
