/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index.js";

export interface GetCallsResponse {
    /** The list of agent calls. */
    data: Cartesia.AgentCall[];
    /** The cursor for the next page of results. */
    nextPage?: string;
}
