/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GitRepository {
    /** The provider of the Git repository, e.g., GitHub. */
    provider: string;
    /** The account name associated with the Git repository. */
    account: string;
    /** The name of the Git repository. */
    name: string;
}
