/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index.js";

export interface ListMetricsResponse {
    /** List of metrics. */
    data: Cartesia.Metric[];
    /** Whether there are more metrics to fetch (using `starting_after=id`, where id is the ID of the last Metric in the current response). */
    hasMore: boolean;
    /** The ID of the last Metric in the current response as a cursor for the next page of results. */
    nextPage?: string;
}
