/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index.js";

export interface ListMetricResultsResponse {
    /** List of metric results. */
    data: Cartesia.MetricResult[];
    /** Whether there are more metric results to fetch (using `starting_after=id`, where id is the ID of the last MetricResult in the current response). */
    hasMore: boolean;
    /** The cursor for the next page of results. */
    nextPage?: string;
}
