/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface LogEvent {
    /** The event name. */
    event: string;
    /** Additional metadata associated with the event. */
    metadata: Record<string, string>;
    /** The timestamp when the event was received relative to the start of the call. */
    timestamp: number;
}
