/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface LogMetric {
    /** The name of the metric. */
    name: string;
    /** The value of the metric. */
    value: number;
    /** The timestamp when the metric was received relative to the start of the call. */
    timestamp: number;
}
