/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index.js";

export interface MetricResult {
    /** The unique identifier for the metric result. */
    id: string;
    /** The identifier of the metric being measured. */
    metricId: string;
    /** The name of the metric being measured. */
    metricName: string;
    /** A summary of the transcript of the call. */
    summary: string;
    /** The transcript of the call. */
    transcript?: Cartesia.AgentTranscript[];
    /** The identifier of the agent associated with the metric result. */
    agentId: string;
    /** The identifier of the call associated with the metric result. */
    callId: string;
    /** The identifier of the deployment associated with the metric result. */
    deploymentId: string;
    /** The raw result of the metric in a string format. */
    result: string;
    /** The structured JSON result of the metric. */
    jsonResult?: Record<string, unknown>;
    /** The value of the metric result. */
    value?: unknown;
    /** The status of the metric result. */
    status: Cartesia.AgentMetricResultStatus;
    /** The identifier of the run associated with the metric result, if applicable. */
    runId?: string;
    /** The UTC timestamp when the metric result was created. */
    createdAt: Date;
}
