/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A phone number that can be used to make calls to your agent.
 */
export interface PhoneNumber {
    /** The ID of the agent. */
    agentId: string;
    /** The phone number. */
    number: string;
    /** The UTC timestamp when the phone number was created. */
    createdAt: Date;
    /** The UTC timestamp when the phone number was last updated. */
    updatedAt: Date;
    /** Whether the phone number is managed by Cartesia. As of now, this is always true since Cartesia provisions phone numbers for you. */
    isCartesiaManaged: boolean;
}
