/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The telephony parameters associated with the call when the call is made via a phone. More details can also be returned depending on the provider.
 */
export interface TelephonyParams {
    /** The phone number of the caller. */
    to: string;
    /** The phone number of the agent. */
    from: string;
}
