/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TextChunk {
    /** The text content of the chunk. */
    text: string;
    /** The starting timestamp of the text chunk in seconds relative to the start of the call. */
    startTimestamp: number;
}
