/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ToolCall {
    /** The unique identifier for the tool call. */
    id: string;
    /** The name of the tool that was called. */
    name: string;
    /** The arguments passed to the tool. */
    arguments: Record<string, string>;
}
