/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../index.js";

export interface UpdateAgentRequest {
    /** The name of the agent. */
    name?: string;
    /** The description of the agent. */
    description?: string;
    /** The voice to use for text-to-speech. */
    ttsVoice?: Cartesia.VoiceId;
    /** The language to use for text-to-speech. */
    ttsLanguage?: string;
}
