/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../../index";

/**
 * @example
 *     {
 *         modelId: "sonic-preview",
 *         language: "en",
 *         transcript: "middle segment",
 *         voiceId: "694f9389-aac1-45b6-b726-9d9369183238",
 *         outputFormatContainer: "mp3",
 *         outputFormatSampleRate: 44100,
 *         outputFormatBitRate: 128000
 *     }
 *
 * @example
 *     {
 *         modelId: "sonic-preview",
 *         language: "en",
 *         transcript: "middle segment",
 *         voiceId: "694f9389-aac1-45b6-b726-9d9369183238",
 *         outputFormatContainer: "wav",
 *         outputFormatSampleRate: 44100,
 *         outputFormatEncoding: "pcm_f32le"
 *     }
 */
export interface InfillBytesRequest {
    /** The ID of the model to use for generating audio */
    modelId: string;
    /** The language of the transcript */
    language: string;
    /** The infill text to generate */
    transcript: string;
    /** The ID of the voice to use for generating audio */
    voiceId: string;
    /** The format of the output audio */
    outputFormatContainer: Cartesia.OutputFormatContainer;
    /** The sample rate of the output audio */
    outputFormatSampleRate: number;
    /**
     * Required for `raw` and `wav` containers.
     *
     */
    outputFormatEncoding?: Cartesia.RawEncoding;
    /**
     * Required for `mp3` containers.
     *
     */
    outputFormatBitRate?: number;
    /**
     * Either a number between -1.0 and 1.0 or a natural language description of speed.
     *
     * If you specify a number, 0.0 is the default speed, -1.0 is the slowest speed, and 1.0 is the fastest speed.
     *
     */
    voiceExperimentalControlsSpeed?: Cartesia.Speed;
    /**
     * An array of emotion:level tags.
     *
     * Supported emotions are: anger, positivity, surprise, sadness, and curiosity.
     *
     * Supported levels are: lowest, low, (omit), high, highest.
     *
     */
    voiceExperimentalControlsEmotion?: Cartesia.Emotion;
}
