/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ListVoicesRequest {
    /** The number of voices to return per page, ranging between 1 and 100. */
    limit?: number;
    /**
     * A cursor to use in pagination. `starting_after` is a voice ID that defines your
     * place in the list. For example, if you make a fine-tune voices request and receive 20
     * objects, ending with `voice_abc123`, your subsequent call can include
     * `starting_after=voice_abc123` to fetch the next page of the list.
     */
    startingAfter?: string;
    /**
     * A cursor to use in pagination. `ending_before` is a voice ID that defines your
     * place in the list. For example, if you make a fine-tune voices request and receive 20
     * objects, starting with `voice_abc123`, your subsequent call can include
     * `ending_before=voice_abc123` to fetch the previous page of the list.
     */
    endingBefore?: string;
}
