/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { VoiceId } from "./VoiceId.js";

export const BaseVoiceId: core.serialization.Schema<serializers.BaseVoiceId.Raw, Cartesia.BaseVoiceId> = VoiceId;

export declare namespace BaseVoiceId {
    export type Raw = VoiceId.Raw;
}
