/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";
import { Embedding } from "../../embedding/types/Embedding";

export const EmbeddingResponse: core.serialization.ObjectSchema<
    serializers.EmbeddingResponse.Raw,
    Cartesia.EmbeddingResponse
> = core.serialization.object({
    embedding: Embedding,
});

export declare namespace EmbeddingResponse {
    interface Raw {
        embedding: Embedding.Raw;
    }
}
