/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const GenderPresentation: core.serialization.Schema<
    serializers.GenderPresentation.Raw,
    Cartesia.GenderPresentation
> = core.serialization.enum_(["masculine", "feminine", "gender_neutral"]);

export declare namespace GenderPresentation {
    export type Raw = "masculine" | "feminine" | "gender_neutral";
}
