/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { VoiceId } from "./VoiceId.js";
import { Weight } from "./Weight.js";

export const IdSpecifier: core.serialization.ObjectSchema<serializers.IdSpecifier.Raw, Cartesia.IdSpecifier> =
    core.serialization.object({
        id: VoiceId,
        weight: Weight,
    });

export declare namespace IdSpecifier {
    export interface Raw {
        id: VoiceId.Raw;
        weight: Weight.Raw;
    }
}
