/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";

export const LocalizeTargetLanguage: core.serialization.Schema<
    serializers.LocalizeTargetLanguage.Raw,
    Cartesia.LocalizeTargetLanguage
> = core.serialization.enum_([
    "en",
    "de",
    "es",
    "fr",
    "ja",
    "pt",
    "zh",
    "hi",
    "it",
    "ko",
    "nl",
    "pl",
    "ru",
    "sv",
    "tr",
]);

export declare namespace LocalizeTargetLanguage {
    export type Raw =
        | "en"
        | "de"
        | "es"
        | "fr"
        | "ja"
        | "pt"
        | "zh"
        | "hi"
        | "it"
        | "ko"
        | "nl"
        | "pl"
        | "ru"
        | "sv"
        | "tr";
}
