/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";
import { LocalizeEnglishDialect } from "./LocalizeEnglishDialect";
import { LocalizeSpanishDialect } from "./LocalizeSpanishDialect";
import { LocalizePortugueseDialect } from "./LocalizePortugueseDialect";

export const LocalizeDialect: core.serialization.Schema<serializers.LocalizeDialect.Raw, Cartesia.LocalizeDialect> =
    core.serialization.undiscriminatedUnion([
        LocalizeEnglishDialect,
        LocalizeSpanishDialect,
        LocalizePortugueseDialect,
    ]);

export declare namespace LocalizeDialect {
    export type Raw = LocalizeEnglishDialect.Raw | LocalizeSpanishDialect.Raw | LocalizePortugueseDialect.Raw;
}
