/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";
import { LocalizeEnglishDialect } from "./LocalizeEnglishDialect";

export const LocalizeDialect: core.serialization.Schema<serializers.LocalizeDialect.Raw, Cartesia.LocalizeDialect> =
    core.serialization.undiscriminatedUnion([LocalizeEnglishDialect]);

export declare namespace LocalizeDialect {
    type Raw = LocalizeEnglishDialect.Raw;
}
