/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const LocalizeSpanishDialect: core.serialization.Schema<
    serializers.LocalizeSpanishDialect.Raw,
    Cartesia.LocalizeSpanishDialect
> = core.serialization.enum_(["mx", "pe"]);

export declare namespace LocalizeSpanishDialect {
    export type Raw = "mx" | "pe";
}
