/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const LocalizePortugueseDialect: core.serialization.Schema<
    serializers.LocalizePortugueseDialect.Raw,
    Cartesia.LocalizePortugueseDialect
> = core.serialization.enum_(["br", "eu"]);

export declare namespace LocalizePortugueseDialect {
    export type Raw = "br" | "eu";
}
