/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";

export const LocalizeEnglishDialect: core.serialization.Schema<
    serializers.LocalizeEnglishDialect.Raw,
    Cartesia.LocalizeEnglishDialect
> = core.serialization.enum_(["au", "in", "so", "uk", "us"]);

export declare namespace LocalizeEnglishDialect {
    type Raw = "au" | "in" | "so" | "uk" | "us";
}
