/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";
import { IdSpecifier } from "./IdSpecifier";
import { EmbeddingSpecifier } from "./EmbeddingSpecifier";

export const MixVoiceSpecifier: core.serialization.Schema<
    serializers.MixVoiceSpecifier.Raw,
    Cartesia.MixVoiceSpecifier
> = core.serialization.undiscriminatedUnion([IdSpecifier, EmbeddingSpecifier]);

export declare namespace MixVoiceSpecifier {
    type Raw = IdSpecifier.Raw | EmbeddingSpecifier.Raw;
}
