/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { GenderPresentation } from "./GenderPresentation.js";

export const UpdateVoiceRequest: core.serialization.ObjectSchema<
    serializers.UpdateVoiceRequest.Raw,
    Cartesia.UpdateVoiceRequest
> = core.serialization.object({
    name: core.serialization.string(),
    description: core.serialization.string(),
    gender: GenderPresentation.optional(),
});

export declare namespace UpdateVoiceRequest {
    export interface Raw {
        name: string;
        description: string;
        gender?: GenderPresentation.Raw | null;
    }
}
