/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const VoiceExpandOptions: core.serialization.Schema<
    serializers.VoiceExpandOptions.Raw,
    Cartesia.VoiceExpandOptions
> = core.serialization.enum_(["is_starred"]);

export declare namespace VoiceExpandOptions {
    export type Raw = "is_starred";
}
