/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const Weight: core.serialization.Schema<serializers.Weight.Raw, Cartesia.Weight> = core.serialization.number();

export declare namespace Weight {
    export type Raw = number;
}
