/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cartesia from "../../../../index";

/**
 * @example
 *     {
 *         "voice[id]": "694f9389-aac1-45b6-b726-9d9369183238",
 *         "output_format[container]": "mp3",
 *         "output_format[sample_rate]": 44100,
 *         "output_format[bit_rate]": 128000
 *     }
 *
 * @example
 *     {
 *         "voice[id]": "694f9389-aac1-45b6-b726-9d9369183238",
 *         "output_format[container]": "wav",
 *         "output_format[sample_rate]": 44100,
 *         "output_format[encoding]": "pcm_f32le"
 *     }
 *
 * @example
 *     {
 *         "voice[id]": "694f9389-aac1-45b6-b726-9d9369183238",
 *         "output_format[container]": "raw",
 *         "output_format[sample_rate]": 44100,
 *         "output_format[encoding]": "pcm_f32le"
 *     }
 */
export interface VoiceChangerSseRequest {
    "voice[id]": string;
    "output_format[container]": Cartesia.OutputFormatContainer;
    "output_format[sample_rate]": number;
    /**
     * Required for `raw` and `wav` containers.
     *
     */
    "output_format[encoding]"?: Cartesia.RawEncoding;
    /**
     * Required for `mp3` containers.
     *
     */
    "output_format[bit_rate]"?: number;
}
