/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { ApiStatus } from "./api/resources/apiStatus/client/Client";
import { Auth } from "./api/resources/auth/client/Client";
import { Infill } from "./api/resources/infill/client/Client";
import { Stt } from "./api/resources/stt/client/Client";
import { Tts } from "./api/resources/tts/client/Client";
import { VoiceChanger } from "./api/resources/voiceChanger/client/Client";
import { Voices } from "./api/resources/voices/client/Client";

export declare namespace CartesiaClient {
    export interface Options {
        environment?: core.Supplier<environments.CartesiaEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey?: core.Supplier<string | undefined>;
        /** Override the Cartesia-Version header */
        cartesiaVersion?: "2024-06-10";
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the Cartesia-Version header */
        cartesiaVersion?: "2024-06-10";
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class CartesiaClient {
    protected _apiStatus: ApiStatus | undefined;
    protected _auth: Auth | undefined;
    protected _infill: Infill | undefined;
    protected _stt: Stt | undefined;
    protected _tts: Tts | undefined;
    protected _voiceChanger: VoiceChanger | undefined;
    protected _voices: Voices | undefined;

    constructor(protected readonly _options: CartesiaClient.Options = {}) {}

    public get apiStatus(): ApiStatus {
        return (this._apiStatus ??= new ApiStatus(this._options));
    }

    public get auth(): Auth {
        return (this._auth ??= new Auth(this._options));
    }

    public get infill(): Infill {
        return (this._infill ??= new Infill(this._options));
    }

    public get stt(): Stt {
        return (this._stt ??= new Stt(this._options));
    }

    public get tts(): Tts {
        return (this._tts ??= new Tts(this._options));
    }

    public get voiceChanger(): VoiceChanger {
        return (this._voiceChanger ??= new VoiceChanger(this._options));
    }

    public get voices(): Voices {
        return (this._voices ??= new Voices(this._options));
    }
}
