/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const CartesiaEnvironment = {
    Production: "https://api.cartesia.ai",
} as const;

export type CartesiaEnvironment = typeof CartesiaEnvironment.Production;
