/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cartesia from "../../../../api/index";
import * as core from "../../../../core";

export const OutputFormatContainer: core.serialization.Schema<
    serializers.OutputFormatContainer.Raw,
    Cartesia.OutputFormatContainer
> = core.serialization.enum_(["raw", "wav", "mp3"]);

export declare namespace OutputFormatContainer {
    type Raw = "raw" | "wav" | "mp3";
}
