/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { Deployment } from "../types/Deployment.js";

export const Response: core.serialization.Schema<
    serializers.agents.listDeployments.Response.Raw,
    Cartesia.Deployment[]
> = core.serialization.list(Deployment);

export declare namespace Response {
    export type Raw = Deployment.Raw[];
}
