/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Cartesia from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { PhoneNumber } from "../types/PhoneNumber.js";

export const Response: core.serialization.Schema<serializers.agents.phoneNumbers.Response.Raw, Cartesia.PhoneNumber[]> =
    core.serialization.list(PhoneNumber);

export declare namespace Response {
    export type Raw = PhoneNumber.Raw[];
}
